export const blog = [
  {
    id: 1,
    type: "admin",
    date: "JAN. 18, 2021",
    com: "3 COMENTÁRIOS",
    title: "Construa a carreira dos seus sonhos em software e engenharia",
    desc: "Um pequeno rio chamado Duden passa por seu lugar e abastece-o com a regelialia necessária.",
    cover: "../images/blog/b1.webp",
  },
  {
    id: 2,
    type: "admin",
    date: "ABR. 25, 2022",
    com: "5 COMENTÁRIOS ",
    title: "Construa a carreira dos seus sonhos em software e engenharia",
    desc: "Um pequeno rio chamado Duden passa por seu lugar e abastece-o com a regelialia necessária.",
    cover: "../images/blog/b2.webp",
  },
  {
    id: 3,
    type: "user",
    date: "FEV. 15, 2022",
    com: "10 COMENTÁRIOS ",
    title: "Construa a carreira dos seus sonhos em software e engenharia",
    desc: "Um pequeno rio chamado Duden passa por seu lugar e abastece-o com a regelialia necessária.",
    cover: "../images/blog/b3.webp",
  },
  {
    id: 4,
    type: "admin",
    date: "JAN. 02, 2022",
    com: "3 COMENTÁRIOS ",
    title: "Construa a carreira dos seus sonhos em software e engenharia",
    desc: "Um pequeno rio chamado Duden passa por seu lugar e abastece-o com a regelialia necessária.",
    cover: "../images/blog/b4.webp",
  },
  {
    id: 5,
    type: "admin",
    date: "DEZ. 14, 2022",
    com: "3 COMENTÁRIOS ",
    title: "Construa a carreira dos seus sonhos em software e engenharia",
    desc: "Um pequeno rio chamado Duden passa por seu lugar e abastece-o com a regelialia necessária.",
    cover: "../images/blog/b5.webp",
  },
  {
    id: 6,
    type: "user",
    date: "JAN. 18, 2021",
    com: "12 COMENTÁRIOS ",
    title: "Construa a carreira dos seus sonhos em software e engenharia",
    desc: "Um pequeno rio chamado Duden passa por seu lugar e abastece-o com a regelialia necessária.",
    cover: "../images/blog/b6.webp",
  },
];
